### ISSUE TITLE
md2.so was published to hex.pm

### ISSUE THREAD

**Issue by fhunleth** [lindenbaum/md2#2]
I'm sure this was an accident, but `priv/md2.so` is included in the package on hex.pm. You can see it at https://preview.hex.pm/preview/md2/1.1.1/show/priv/md2.so. The preview screen is reached by going to your package on hex.pm and clicking on `<>`. 

This is causing builds to not work that don't match the architecture of the bundled `md2.so` file. Could you publish a new hex package without it?

**Comment by schlagert** [comment]
Thanks for the tip and sorry for the inconvenience. That was not intentional, I'll have a look into it tomorrow.

**Comment by fhunleth** [comment]
Thanks for the quick response! No inconvenience - just a little confusion at first.

**Comment by schlagert** [comment]
I just published a new version [1.2.0](https://hex.pm/packages/md2/1.2.0) and will update the `eipmi` dependency accordingly in a few minutes.
